function valida_cpf(double cpf){

  sdfjkshfgçlkfhsdçglhçfds
  sfdgkfçsdjgçdsfjgçlksfdjçgljdsfdfsgçdsfçjglkfdsj
  dlkfsjgçdsfkjgçlfjkdsçgjdsfçjkgçsjfdgçljfsdçljgçlsfdjkgçlk
  dflkjgçsdfkjgçjfdsçgjçsfdjgçsdjfçgjsdfçkjgçsdfjgçlkdfjgkfkkdsfopsrjflçsdjf
 
}
